import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

import Header from "@/components/layout/header/header";
import Footer from "@/components/layout/footer/footer";
import SidebarContainer from "@/components/layout/sidebar/side-container";

import { auth } from "@/lib/auth";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@/provider/theme-provider";
import { QueryProvider } from "@/provider/queryProvider";
import { Toaster } from "react-hot-toast";

import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Shadowing - Be Mroe Terrific",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" suppressHydrationWarning>
      <meta
        name="viewport"
        content="width-device-width, height=device-height, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"
      />
      <body
        className={cn("min-h-screen font-sans antialiased", inter.variable)}
      >
        <NextTopLoader />
        <SessionProvider session={session}>
          <QueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <div className="flex flex-row">
                <SidebarContainer />
                <div className="flex-grow overflow-hidden">
                  <Header />
                  <main className="mx-auto flex min-h-screen flex-col">
                    {children}
                  </main>

                  <Footer />
                </div>
              </div>

              <Toaster />
            </ThemeProvider>
          </QueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
